FROM python:3.7

RUN mkdir -p /home/ubuntu/object_detection/

WORKDIR /home/ubuntu/object_detection/

ADD . /home/ubuntu/object_detection/

RUN pip3 install -r /home/ubuntu/object_detection/requirements.txt && pip install coco

RUN apt-get update
RUN apt-get install -y libgl1-mesa-dev

ENV HOME=/home/ubuntu
ENV APP_HOME=$HOME/object_detection
RUN mkdir $APP_HOME
RUN mkdir $APP_HOME/static
RUN mkdir $APP_HOME/media
WORKDIR $APP_HOME